apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vanguard
  labels:
    app: redis
    app.kubernetes.io/part-of: vanguard-bot
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
