apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanguard-data
  namespace: vanguard
  labels:
    app.kubernetes.io/part-of: vanguard-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: fast-ssd   # раскомментировать для конкретного cloud-провайдера
