{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "vanguard-bot.namespace" . }}
  labels:
    {{- include "vanguard-bot.labels" . | nindent 4 }}
{{- end }}
